apiVersion: apps/v1
kind: Deployment
metadata:
    name: _APP_NAME_
    labels:
        app: _APP_NAME_
spec:
    replicas: 3
    selector:
        matchLabels:
            app: _APP_NAME_

    # Pod template
    template:
        metadata:
            labels:
                app: _APP_NAME_
        spec:
            containers:
                - name: scraper
                  image: _REGISTRY_IMAGE_
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 7006
                  env:
                      - name: JWT_SECRET
                        value: _JWT_SECRET_
                      - name: RESOURCE_BROKER_TOKEN
                        value: _RESOURCE_BROKER_TOKEN_
                      - name: DISCOVERY_HOST
                        value: _DISCOVERY_HOST_
                      - name: DISCOVERY_PORT
                        value: "_DISCOVERY_PORT_"
                      - name: DISCOVERY_TOKEN
                        value: _DISCOVERY_TOKEN_
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
            imagePullSecrets:
                - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
    name: _APP_NAME_
    labels:
        app: _APP_NAME_
spec:
    type: NodePort
    ports:
        - port: 7006
          targetPort: 7006
          nodePort: 27006
          protocol: TCP
          name: http
    selector:
        app: _APP_NAME_
