apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "distributor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "distributor.name" . }}
    helm.sh/chart: {{ include "distributor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "distributor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "distributor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JWT_SECRET
              value: "{{ .Values.jwtSecret }}"
            - name: API_PORT
              value: "{{ .Values.service.port }}"
            - name: DISCOVERY_TOKEN
              value: "{{ .Values.discoveryToken }}"
            - name: DISCOVERY_HOST
              value: "{{ .Values.discoveryHost }}"
            - name: DISCOVERY_PORT
              value: "{{ .Values.discoveryPort }}"
            - name: BUILD_REF
              value: "{{ .Values.image.tag }}"
            - name: RESOURCE_BROKER_TOKEN
              value: "{{ .Values.resourceBrokerToken }}"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.probePort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.probePort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
